AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"

Description: Provision a lambda from S3

Parameters:
  pArtifactS3BucketName:
    Description: the name of our S3 bucket for the lambda function
    Type: String

  pArtifactS3Key:
    Description: The object key for our lambda source code from S3
    Type: String

  pLogLevel:
    Description: the logging level for our lambda function
    Type: String
    Default: Info
    AllowedValues:
      - Debug
      - Info
      - Warning
      - Error
      - Critical

Resources:
  rLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: create-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvent
              Effect: Allow
              Resource: arn:aws:logs:*:*:*

  rLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref pArtifactS3BucketName
        Key: !Ref pArtifactS3Key
      Environment:
        Variables:
          LOG_LEVEL: !Ref pLogLevel
      Handler: lambda.handler
      Role: !GetAtt rLambdaFunctionRole.Arn
      Runtime: python3.7
      Tags:
        CreatedByCloudFormation: "True"
        Name: SimpleLambdaFunction

  rLambdaFunctionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref rLambdaFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 300
      Statistic: Sum
      Threshold: 0

Outputs:
  LambdaIAMRoleARN:
    Description: This is the ARN for the IAM Role for the lambda function
    Value: !GetAtt rLambdaFunctionRole.Arn

  LambdaFunctionARN:
    Description: This is the ARN for the lambda function we deployed
    Value: !GetAtt rLambdaFunction.Arn

  LambdaAlarmARN:
    Description: The ARN for the cloudwatch alarm
    Value: !GetAtt rLambdaFunctionErrorAlarm.Arn